apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oec.fullname" . }}-cms-volume
  labels:
    {{- include "oec.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "80Gi" .Values.storage }}
status: {}
