apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oec.fullname" . }}-web-configmap
  labels:
    {{- include "oec.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "conf/*").AsConfig | indent 2 }}