apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oec.fullname" . }}-web-configmap
  labels:
    {{- include "oec.labels" . | nindent 4 }}
binaryData:
  {{- range $key, $value := .Values.httpdConf }}
  {{ $key }}: {{$value | b64enc}}
  {{ end }}
