apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oec.fullname" . }}
  labels:
    {{- include "oec.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "oec.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "oec.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oec.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ printf "%s-cms" .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.cms.repository }}:{{ .Values.image.cms.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /system/health
              port: http
          readinessProbe:
            httpGet:
              path: /system/health
              port: http
          resources:
            {{- toYaml .Values.resources.cms | nindent 12 }}
          volumeMounts:
            - name: {{ printf "%s-cms-secrets" .Chart.Name }}
              mountPath: /opt/secrets
            - name: {{ printf "%s-cms-volume" .Chart.Name }}
              mountPath: /opt/oec/launcher/composite/repository-global
        - name: {{ printf "%s-web" .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
          volumeMounts:
            - name: {{ printf "%s-web-config-volume" .Chart.Name }}
              mountPath: /etc/apache2/sites-enabled
      volumes:
        - name: {{ printf "%s-cms-secrets" .Chart.Name }}
          secret:
            secretName: {{ include "oec.fullname" . }}-cms-secrets
        - name: {{ printf "%s-cms-volume" .Chart.Name }}
          persistentVolumeClaim:
            claimName: {{ include "oec.fullname" . }}-cms-volume
        - name: {{ printf "%s-web-config-volume" .Chart.Name }}
          configMap:
            name: {{ include "oec.fullname" . }}-web-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
