apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oec.fullname" . }}-cms-secrets
  labels:
    {{- include "oec.labels" . | nindent 4 }}
type: Opaque
binaryData:
  {{- range $key, $value := .Values.cmsSecrets }}
  {{ $key }}: {{$value | b64enc}}
  {{ end }}