apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oec.fullname" . }}-cms-secrets
  labels:
    {{- include "oec.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}