# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Helm Template Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install helm
      uses: azure/setup-helm@v1
      id: install
    - name: Login to Github Container Registry (in Helm)
      run: echo ${{ secrets.HELM_TOKEN }} | helm registry login -u ${{ secrets.HELM_USERNAME }} --password-stdin https://openexperiencecloud.jfrog.io
    - name: Lint Chart
      run: helm lint .
    - name: Save Chart
      run: helm chart save . openexperiencecloud.jfrog.io/helm/cloud-openexperience-charts-standalone:latest
    - name: Push Chart
      run: helm chart push openexperiencecloud.jfrog.io/helm/cloud-openexperience-charts-standalone:latest
    env:
      HELM_EXPERIMENTAL_OCI: '1'
